site_name: Kstych

docs:
    images/
        login_page.png
nav:
    - Getting Started: index.md
    - Understanding the Kstych Framework: understand-kstych.md
    - Commonly Used Libraries in Kstych Framework: commonly-used-libraries.md
    - Menus in the Kstych Application: kstych-menus.md
    - Building Your First Kstych Application: demo-app.md
    - --Pending doc--: pending_doc.md

# Plugins
#plugins:
#    - pygments


# Extensions
markdown_extensions:
  - codehilite

# Theme Configuration
theme:
    name: readthedocs
    highlightjs: true
    hljs_style: true
    hljs_languages:
        - yaml
        - rust
        - python
        - php
    features:
        - content.code.annotate
    font:
      text: Times New Roman

# Customization
extra_css:
  - stylesheets/extra.css
