site_name: Kstych

docs:
    images/
        login_page.png
nav:
    - Getting Started: index.md
    - Understanding the Kstych Framework: understand-ksytych.md
    - Commonly Used Libraries in Kstych Framework: commonly-used-libraries.md
    - Menus in the Kstych Application: ksytych-menus.md

# Plugins
#plugins:
#    - pygments


# Extensions
markdown_extensions:
  - codehilite

# Theme Configuration
theme:
    name: readthedocs
    highlightjs: true
    hljs_style: true
    hljs_languages:
        - yaml
        - rust
        - python
        - php
    features:
        - content.code.annotate
    font:
      text: Times New Roman

# Customization
extra_css:
  - stylesheets/extra.css
